<?php

/**
 * @file
 * Initializes UI tweaks provided by the module.
 *
 * Copyright (C) 2013, Victor Nikulshin
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Implements hook_widget_form_alter().
 */
function taxonomy_options_ui_tweaks_field_widget_form_alter(&$element, &$form_state, $context) {
  $field  = $context['field'];
  $widget = $context['instance']['widget'];

  if (_taxonomy_options_ui_tweaks_supported($field, $widget)) {
    $path = drupal_get_path('module', 'taxonomy_options_ui_tweaks');
    $path .= '/js/ui-tweaks.js';

    // drupal_add_js() makes sure that any file is included on the page only
    // once, so we do not need to worry about it.
    drupal_add_js($path);
  }
}

/**
 * Checks that the tweaking of a particular field and widget is supported.
 *
 * This module can safely tweak only several widgets that are used to input
 * data into some supported fields. In a particular combination is not
 * supported there is no need to anything.
 */
function _taxonomy_options_ui_tweaks_supported($field, $widget) {
  if ($field['type'] == 'taxonomy_term_reference') {
    if ($widget['type'] == 'options_buttons') {
      return TRUE;
    }
  }

  return FALSE;
}
